version: '3.8'

services:
  elasticsearch:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ELK_VERSION: ${ELK_VERSION}  # .env에서 읽은 환경변수 전달
    container_name: pawong-elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
      - xpack.security.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTICSEARCH_PLUGINS=analysis-nori  # 플러그인 설치 명시
    volumes:
      - ./config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./data:/usr/share/elasticsearch/data
    ports:
      - "${ELASTIC_PORT}:9200"
    networks:
      - elk-network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9200 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: kibana:${ELK_VERSION}
    container_name: pawong-kibana
    depends_on:
      - elasticsearch
    ports:
      - "${KIBANA_PORT}:5601"
    networks:
      - elk-network
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

networks:
  elk-network:
    driver: bridge
