spring:
  application:
    name: pawong-backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/likelion?serverTimezone=Asia/Seoul
    username: likelion
    password: likelion
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      embedding-model-name: text-embedding-ada-002