spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: o4-mini
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-ada-002

auth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    redirect-url: ${KAKAO_REDIRECT_URL}
    token-url: ${KAKAO_TOKEN_URL}
    user-info-url: ${KAKAO_API_URL}