spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_DB_USERNAME}
    password: ${DEV_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: o4-mini
          temperature: 1.0
      embedding:
        options:
          model: text-embedding-ada-002
  jpa:
    show-sql: true                # 콘솔에 SQL 찍기
    properties:
      hibernate:
        format_sql: true          # 보기 좋게 포맷팅
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID} # REST API key
            client-secret: ${KAKAO_CLIENT_SECRET} # Admin key
            authorization-grant-type: authorization_code
            redirect-uri: "${BASE_URL}/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            scope: profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id