services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./logs/nginx:/var/log/nginx   # 로그를 호스트 ./logs/nginx 에 마운트
